Add code for meeting scheduler project
anishajain22/software-product-sprint pull request #2
Opened 2020-07-17 14:23 UTC by anishajain22

2020-07-17 16:11 UTC, yashjaing commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        ArrayList<TimeRange> allTimeSlots = new ArrayList<TimeRange>();;
just new ArrayList<>() should work. Remove the extra ;

2020-07-17 16:12 UTC, yashjaing commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +
nit: extra line

2020-07-17 16:13 UTC, yashjaing commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        //throw new UnsupportedOperationException("TODO: Implement this method.");
remove?

2020-07-17 16:15 UTC, yashjaing commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +import java.util.*;
avoid * imports

2020-07-17 16:19 UTC, yashjaing commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        }
this can be simplified using a java 8 streams. Something similar to - https://www.baeldung.com/java-lists-intersection

2020-07-17 16:20 UTC, yashjaing requested changes
Couple of things -
1. Break the method down into small private methods
2. Better variable names :)

2020-07-18 08:32 UTC, anishajain22 commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        ArrayList<TimeRange> allTimeSlots = new ArrayList<TimeRange>();;
Done.

2020-07-18 08:32 UTC, anishajain22 commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +
Agreed.

2020-07-18 08:32 UTC, anishajain22 commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +import java.util.*;
Alright.

2020-07-18 08:32 UTC, anishajain22 commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        }
Added in the next set of commits.

2020-07-19 12:46 UTC, yashjaing commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        ArrayList<TimeRange> mergedAllRequestTimeRanges = new ArrayList<>();
List<T> l = new ArrayList<>(); same at other places.

2020-07-19 12:47 UTC, yashjaing approved these changes
Please fix the formatting. Pick up a java formatter with line length 120 and format the java file.

2020-07-19 13:20 UTC, anishajain22 commented on walkthroughs/week-4-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        ArrayList<TimeRange> mergedAllRequestTimeRanges = new ArrayList<>();
Changes made.

2020-07-19 13:23 UTC, merged